---

# secondary master
#
- name: define PKI facts
  ansible.builtin.set_fact:
    icinga2_pki_ca_key: "{{ icinga2_pki_dir }}/ca.key"
    icinga2_pki_ca_cert: "{{ icinga2_pki_dir }}/ca.crt"
    icinga2_pki_fqdn_key: "{{ icinga2_pki_dir }}/{{ ansible_fqdn }}.key"
    # icinga2_pki_fqdn_cert: "{{ icinga2_pki_dir }}/{{ ansible_fqdn }}.crt"
    # icinga2_pki_master_cert: "{{ icinga2_pki_dir }}/trusted-master.crt"

- name: "create '{{ icinga2_pki_dir }}'"
  ansible.builtin.file:
    dest: "{{ icinga2_pki_dir }}"
    state: directory
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_group }}"
    mode: 0750

- name: "check for existing '{{ icinga2_pki_fqdn_key }}'"
  ansible.builtin.stat:
    path: "{{ icinga2_pki_fqdn_key }}"
  register: __fqdn_key

- name: "check for existing '{{ icinga2_pki_ca_cert }}'"
  ansible.builtin.stat:
    path: "{{ icinga2_pki_ca_cert }}"
  register: __ca_crt

- name: create a ticket from icinga2 master for the secondary master
  when:
    - not __fqdn_key.stat.exists
    - icinga2_primary_master is defined
    - icinga2_primary_master != ansible_fqdn
  block:
    - name: "create a ticket from icinga2 master for the secondary master '{{ ansible_fqdn }}'"
      delegate_to: "{{ icinga2_primary_master }}"
      icinga2_ticket:
        common_name: "{{ icinga2_certificate_cn }}"
        salt: "{{ icinga2_salt }}"
      register: ticket

    - name: define FQDN ticket
      ansible.builtin.set_fact:
        icinga2_fqdn_ticket: "{{ ticket.ticket }}"

    - name: copy ca.crt from primary icinga2 master
      delegate_to: '{{ icinga2_primary_master }}'
      ansible.builtin.fetch:
        src: "{{ icinga2_pki_ca_cert }}"
        dest: files/ca.crt
        flat: true

    - name: "copy ca.crt to '{{ ansible_fqdn }}'"
      ansible.builtin.copy:
        src: files/ca.crt
        dest: "{{ icinga2_pki_ca_cert }}"
        owner: "{{ icinga2_user }}"
        group: "{{ icinga2_group }}"
        mode: 0660

    - name: configure icinga2 secondary master pki
      become: true
      icinga2_node_setup:
        common_name: "{{ icinga2_certificate_cn }}"
        ca_key: "{{ icinga2_pki_ca_key }}"
        ticket: "{{ icinga2_fqdn_ticket }}"
        parent_icinga2_host: "{{ icinga2_primary_master }}"
        zone: "{{ icinga2_primary_master }}"
        endpoint: "{{ icinga2_primary_master }}"
      when:
        - not __fqdn_key.stat.exists
        - icinga2_fqdn_ticket is defined
      notify:
        - check configuration
        - restart icinga2

    - name: fix permissions for icinga2 pki directory
      ansible.builtin.file:
        path: "{{ icinga2_pki_dir }}"
        owner: "{{ icinga2_user }}"
        group: "{{ icinga2_group }}"
        recurse: true

    - name: configure zones
      ansible.builtin.template:
        src: etc/icinga2/zones.conf.j2
        dest: /etc/icinga2/zones.conf
        owner: "{{ icinga2_user }}"
        group: "{{ icinga2_group }}"
        mode: 0666
        backup: true
  rescue:

    - name: remove pki directory
      ansible.builtin.file:
        state: absent
        path: "{{ icinga2_pki_dir }}"

    - name: remove zones config
      ansible.builtin.file:
        state: absent
        path: /etc/icinga2/zones.conf

    - name: exit with fail
      ansible.builtin.fail:
        msg: "Error when creating a ticket from icinga2 master !"

- name: create host object file for secondary master on master '{{ icinga2_primary_master }}'
  delegate_to: "{{ icinga2_primary_master }}"
  ansible.builtin.template:
    src: etc/icinga2/zones.d/secondary.conf.j2
    dest: /etc/icinga2/zones.d/primary/{{ ansible_fqdn }}.conf
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_group }}"
    mode: 0666
  notify:
    - reload icinga2 master config
  when:
    - icinga2_primary_master is defined
    - icinga2_primary_master != ansible_fqdn

- name: create icinga2 constants.conf
  ansible.builtin.template:
    src: etc/icinga2/constants.conf.j2
    dest: /etc/icinga2/constants.conf
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_group }}"
    mode: 0666
  notify:
    - check configuration

- name: secondary master features
  ansible.builtin.include_tasks: features.yml

...
