---

- name: detect if icinga2 exists
  stat:
    path: /usr/sbin/icinga2
  register: icinga2_binary_file

- name: set icinga2_installed
  set_fact:
    icinga2_installed: "{{ icinga2_binary_file.stat.exists }}"

- name: do facts module to get latest information
  setup:

- block:
    #
    - name: detect installed icinga2 version  # noqa 301 306
      shell: >
        icinga2 --version | head -n1 | awk -F 'version: ' '{printf $2}' | awk -F '-' '{print $1}' | sed 's|r||'
      register: __installed_icinga2_version

    - name: set icinga2 version
      set_fact:
        icinga2_installed_version: "{{ __installed_icinga2_version.stdout }}"
        cacheable: true
      when: __installed_icinga2_version is defined and
        __installed_icinga2_version.rc is defined and
        __installed_icinga2_version.rc == 0

    - name: installed icinga2 version
      debug:
        var: icinga2_installed_version
      when: icinga2_installed_version is defined and icinga2_installed_version | length != 0

  when:
    icinga2_installed
