---

- name: define graphite feature state
  ansible.builtin.set_fact:
    feature_graphite_state: "{{ 'present' if icinga2_master_features_enabled | join('|') | regex_search('graphite') else 'absent' }}"

- name: configure graphite feature
  ansible.builtin.template:
    src: etc/icinga2/features/graphite.conf.j2
    dest: /etc/icinga2/features-available/graphite.conf
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_group }}"
    mode: 0660

- name: enable graphite feature
  icinga2_features:
    features:
      - graphite
    state: "{{ feature_graphite_state }}"
  notify:
    - check configuration
    - restart icinga2
  tags:
    - icinga2
    - features
