---

- name: create notifications directory
  ansible.builtin.file:
    name: /etc/icinga2/notifications
    state: directory
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_group }}"
    mode: 0750

- name: define notifications feature state
  ansible.builtin.set_fact:
    feature_notification_state: "{{ 'present' if icinga2_master_features_enabled | join('|') | regex_search('notification') else 'absent' }}"

- name: merge icinga2 notification configuration between defaults and custom
  ansible.builtin.set_fact:
    icinga2_notification_templates: "{{ icinga2_defaults_notification_templates | combine(icinga2_notification_templates, recursive=True) }}"
    icinga2_notification_objects: "{{ icinga2_defaults_notification_objects | combine(icinga2_notification_objects, recursive=True) }}"
    icinga2_notification_apply_rules: "{{ icinga2_defaults_notification_apply_rules | combine(icinga2_notification_apply_rules, recursive=True) }}"

- name: configure notification feature
  ansible.builtin.template:
    src: etc/icinga2/features/notification.conf.j2
    dest: /etc/icinga2/features-available/notification.conf
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_group }}"
    mode: 0666

- name: configure notification templates
  ansible.builtin.template:
    src: etc/icinga2/notifications/notification-templates.conf.j2
    dest: /etc/icinga2/notifications/notification-templates.conf
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_group }}"
    mode: 0666
  notify:
    - check configuration
    - reload icinga2

- name: configure notification objects
  ansible.builtin.template:
    src: etc/icinga2/notifications/notification-objects.conf.j2
    dest: /etc/icinga2/notifications/notification-objects.conf
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_group }}"
    mode: 0666
  notify:
    - check configuration
    - reload icinga2

- name: configure notification apply rules
  ansible.builtin.template:
    src: etc/icinga2/notifications/notification-apply-rules.conf.j2
    dest: /etc/icinga2/notifications/notification-apply-rules.conf
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_group }}"
    mode: 0666
  notify:
    - check configuration
    - reload icinga2

- name: enable notification feature
  icinga2_features:
    features:
      - notification
    state: "{{ feature_notification_state }}"
  notify:
    - check configuration
    - restart icinga2
  tags:
    - icinga2
    - features
