---
- hosts: all
  any_errors_fatal: false
  environment:
    NETRC: ''
  vars:

    mysql_bind_address: 127.0.0.1
    mysql_max_connections: 20

    mysql_root_password_update: true

    mysql_databases:
      - name: icinga2_ido

    mysql_users:
      - name: icinga2_ido
        host: 127.0.0.1
        password: icinga2
        priv: "icinga2_ido.*:ALL"

    icinga2_mode: master

    icinga2_masters:
      #debian-10:
      centos-7:

    icinga2_sudo_cmd:
      - /sbin/service foo restart

    icinga2_api:
      user:
        root:
          password: foo
          permissions: '*'

    icinga2_ido:
      username: icinga2_ido
      password: icinga2
      # socket: /var/lib/mysql/mysql.sock
      cleanup:
        acknowledgements_age: 48h
        hostchecks_age: 48h
        servicechecks_age: 48h

    icinga2_master_features_enabled:
      - checker
      - api
      - ido-mysql
      - mainlog

    icinga2_host_object:
      localhost:
        import: generic-host
        address: '{{ ansible_default_ipv4.address }}'
        display_name: "{{ ansible_fqdn }}"
        vars: |
          os = "Linux"
          dist = "{{ ansible_distribution }}"
          dist_ver = "{{ ansible_distribution_version }}"
          disks = {
            "disk /" = {
              disk_partitions = "/"
            }
          }

    icinga2_salt: tmpams80tqx

  roles:
    - role: mariadb
    - role: ansible-icinga2

  # tasks:
  #   # - include: ../../tasks/master/features.yml
  #   #   tags:
  #   #     - features
  #   - include: ../../tasks/downtime.yml
  #     vars:
  #       icinga2_master: '{{ ansible_default_ipv4.address }}'
  #       icinga2_api.user: root
  #       icinga2_api.password: foo
  #       icinga2_downtime_comment: Downtime for deployment
  #       icinga2_downtime_system_name: localhost
  #       icinga2_downtime_duration: 120
  #
  #     tags:
  #       - downtime_schedule

