---
- name: Debian | Extra packages install
  apt: name={{item}} state=present update_cache=yes install_recommends=no
  with_items:
    - snmpd
    - nagios-plugins
    - nagios-nrpe-server
    - nagios-nrpe-plugin
    - nsca-ng-client
    - perl
    - libdatetime-format-strptime-perl
    - libnagios-plugin-perl
    - openssh-server
    - lm-sensors
    - libhtml-strip-perl
    - acl

- name: Debian | Extra packages install
  apt: name={{item}} state=present
  with_items:
    - openntpd
  when: monitor_ntp

#- user: name=nagios groups=ossec append=yes

- name: Review ntpd configuration
  replace:
    dest='/etc/openntpd/ntpd.conf' regexp="{{ item.regexp }}" replace='{{ item.replace }}'
  with_items:
    - { regexp: '^#listen on 127.0.0.1', replace: 'listen on 127.0.0.1' }
  notify:
    - restart openntpd
  when: monitor_ntp

- copy: src=local-nrpe.cfg dest=/etc/nagios/nrpe.d/local-nrpe.cfg mode=0644
  notify:
    - restart nrpe
- name: Review nrpe configuration
  replace:
    dest='/etc/nagios/nrpe.cfg' regexp='{{ item.regexp }}' replace='{{ item.replace }}' backup=yes
  with_items:
    - { regexp: '^allowed_hosts=127.0.0.1.*$', replace: 'allowed_hosts=127.0.0.1,{{Â MONSERVER }}' }
  notify:
    - restart nrpe


