---

- name: Ubuntu i386/x86_64 | add icinga packages repository
  apt_repository: repo='deb http://packages.icinga.org/ubuntu icinga-trusty main' state=present
  when: ansible_distribution == 'Ubuntu' and (ansible_architecture == 'i386' or ansible_architecture == 'x86_64')

- name: Ubuntu i386/x86_64 | add icinga packages repository key
  apt_key: url=http://packages.icinga.org/icinga.key state=present
  when: ansible_distribution == 'Ubuntu' and (ansible_architecture == 'i386' or ansible_architecture == 'x86_64')

- name: Debian | Extra packages install
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - icinga2
  when: ansible_distribution == 'Ubuntu' and (ansible_architecture == 'i386' or ansible_architecture == 'x86_64')

- include: client-nrpe.yml

- include: client-icinga2node.yml
#- include: client-agentless.conf
